# Generated by Django 4.2.5 on 2023-09-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("tier", models.IntegerField()),
                ("stripe_product_id", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "DAILY"),
                            (2, "WEEKLY"),
                            (3, "MONTHLY"),
                            (4, "QUARTERLY"),
                            (5, "SEMI"),
                            (6, "YEARLY"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "RecurringPayment"), (2, "OneTimePayment")],
                        default=1,
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=256)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="payments.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=256)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="payments.product",
                    ),
                ),
            ],
        ),
    ]
