# Generated by Django 4.2.5 on 2024-01-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_title", models.CharField(max_length=256)),
                ("feature_description", models.CharField(max_length=256)),
                ("feature_mui_icon_name", models.CharField(max_length=256)),
                ("order", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HowItWorks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=256)),
                ("step_description", models.CharField(max_length=256)),
                ("step_mui_icon_name", models.CharField(max_length=256)),
                ("order", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_hero_title", models.CharField(max_length=256)),
                ("primary_hero_subtitle", models.CharField(max_length=256)),
                (
                    "primary_hero_image",
                    models.ImageField(upload_to="landingpage_images/"),
                ),
                ("secondary_hero_title", models.CharField(max_length=256)),
                ("secondary_hero_subtitle", models.CharField(max_length=256)),
                (
                    "secondary_hero_image",
                    models.ImageField(upload_to="landingpage_images/"),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="landingepage_features", to="landingpage.features"
                    ),
                ),
                (
                    "how_it_works",
                    models.ManyToManyField(
                        related_name="landingepage_how_it_works",
                        to="landingpage.howitworks",
                    ),
                ),
            ],
        ),
    ]
