# Generated by Django 4.2.5 on 2024-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
